#!/bin/bash
gsql create_schema.gsql
gsql create_database.gsql

gsql --graph LDBC_SNB load_static_1.gsql
gsql --graph LDBC_SNB load_static_2.gsql
gsql --graph LDBC_SNB load_dynamic_1.gsql

gsql --graph LDBC_SNB 'RUN LOADING JOB load_static_1 USING organisation="ANY:social_network/static/organisation_0_0.csv", place="ANY:social_network/static/place_0_0.csv", tagclass="ANY:social_network/static/tagclass_0_0.csv", tagclass_isSubclassOf_tagclass="ANY:social_network/static/tagclass_isSubclassOf_tagclass_0_0.csv", tag="ANY:social_network/static/tag_0_0.csv", tag_hasType_tagclass="ANY:social_network/static/tag_hasType_tagclass_0_0.csv"'
gsql --graph LDBC_SNB 'RUN LOADING JOB load_static_2 USING organisation_isLocatedIn_place="ANY:social_network/static/organisation_isLocatedIn_place_0_0.csv", place_isPartOf_place="ANY:social_network/static/place_isPartOf_place_0_0.csv"'
gsql --graph LDBC_SNB 'RUN LOADING JOB load_dynamic_1 USING comment="ANY:social_network/dynamic/comment_0_0.csv", comment_hasCreator_person="ANY:social_network/dynamic/comment_hasCreator_person_0_0.csv", comment_hasTag_tag="ANY:social_network/dynamic/comment_hasTag_tag_0_0.csv", comment_isLocatedIn_place="ANY:social_network/dynamic/comment_isLocatedIn_place_0_0.csv", comment_replyOf_comment="ANY:social_network/dynamic/comment_replyOf_comment_0_0.csv", comment_replyOf_post="ANY:social_network/dynamic/comment_replyOf_post_0_0.csv", forum="ANY:social_network/dynamic/forum_0_0.csv", forum_containerOf_post="ANY:social_network/dynamic/forum_containerOf_post_0_0.csv", forum_hasMember_person="ANY:social_network/dynamic/forum_hasMember_person_0_0.csv", forum_hasModerator_person="ANY:social_network/dynamic/forum_hasModerator_person_0_0.csv", forum_hasTag_tag="ANY:social_network/dynamic/forum_hasTag_tag_0_0.csv", person="ANY:social_network/dynamic/person_0_0.csv", person_hasInterest_tag="ANY:social_network/dynamic/person_hasInterest_tag_0_0.csv", person_isLocatedIn_place="ANY:social_network/dynamic/person_isLocatedIn_place_0_0.csv", person_knows_person="ANY:social_network/dynamic/person_knows_person_0_0.csv", person_likes_comment="ANY:social_network/dynamic/person_likes_comment_0_0.csv", person_likes_post="ANY:social_network/dynamic/person_likes_post_0_0.csv", person_studyAt_organisation="ANY:social_network/dynamic/person_studyAt_organisation_0_0.csv", person_workAt_organisation="ANY:social_network/dynamic/person_workAt_organisation_0_0.csv", post="ANY:social_network/dynamic/post_0_0.csv", post_hasCreator_person="ANY:social_network/dynamic/post_hasCreator_person_0_0.csv", post_hasTag_tag="ANY:social_network/dynamic/post_hasTag_tag_0_0.csv", post_isLocatedIn_place="ANY:social_network/dynamic/post_isLocatedIn_place_0_0.csv"'